        const responses = {
            "rialo": "RIALO is a next-generation Layer 1 Blockchain infrastructure specifically engineered to solve the 'Data Transparency Trilemma' in Web3. It operates as a high-performance decentralized ledger that ensures every byte of information—from market analytics to transaction hashes—is immutable and globally accessible. By utilizing a unique consensus mechanism, Rialo provides the foundational security layer for the Market Predict ecosystem, allowing for institutional-grade data verification without central authority interference.",
            
            "what is rialo": "At its core, RIALO is the ultimate neural highway for decentralized intelligence. It isn't just a blockchain; it is a scalable network designed to process massive market data streams in milliseconds. Our 'Alpha Engine' lives on Rialo to ensure that every prediction is cross-referenced against real-time on-chain activity. This architecture eliminates 'black-box' manipulation, providing users with a transparent window into market anomalies and high-probability Alpha signals that were previously only accessible to hedge funds.",
            
            "whats rialo": "RIALO stands as the definitive bridge between raw global market data and decentralized decision-making. Its primary mission is to democratize financial intelligence. By leveraging Rialo's Layer 1 capabilities, our platform can execute complex analytical scripts directly on the network. This ensures that the 'Market Predict' outcomes are 100% tamper-proof, verified by a distributed network of validator nodes, and secured by state-of-the-art cryptographic proofs. It is the backbone of the Alpha Revolution.",
            
            "prediction": "The Alpha Core Prediction system is powered by a proprietary neural network architecture integrated deeply within the Rialo Mainnet. It constantly scans for 'Alpha'—hidden market patterns and liquidity shifts—across multiple digital asset pairs. Every generated signal undergoes a three-tier verification process: (1) Historical Pattern Matching, (2) Real-time Liquidity Analysis, and (3) On-chain Validation via Rialo. Current performance metrics show a sustained success probability of 89.4%, making it one of the most accurate decentralized engines in the Web3 space.",
            
            "safety": "Security in the Rialo Ecosystem is non-negotiable and strictly non-custodial. The system architecture is built so that Alpha Core AI only provides 'Intelligence as a Service' (IaaS). We never request access to your private keys, seed phrases, or personal assets. All smart contracts governing the Rialo network are immutable and open-source, providing a 'Trust-less' environment. Your security is guaranteed by the mathematical certainty of the blockchain, protected against 51% attacks and unauthorized data tampering.",
            
            "roadmap": "The Rialo Project is currently in the 'Alpha Integration' phase. Our roadmap includes: (Q2 2026) Expansion of the Rialo Validator Node network to increase decentralization, (Q3 2026) Integration of Cross-chain Alpha Signals for Layer 2 scaling solutions, and (Q4 2026) The launch of 'Rialo Shark Tank'—a community-driven builder event to fund the next generation of decentralized apps on our Layer 1. We are building for the long-term stability of the decentralized economy.",
            
            "hello": "Alpha Core Terminal: ONLINE. Synchronizing with Rialo Mainnet nodes... [OK]. Database Integrity: 100%. I am your primary interface for Rialo Ecosystem Intelligence. I can explain our Layer 1 architecture, the Alpha Prediction mechanics, or our security protocols. What is your command, User?"
        };
